name: swdtorch12
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia

# Dependencies
# - python=3.11
# - pytorch
# - torchvision
# - torchaudio
# - pytorch-cuda=12.1

# Pip dependencies
pip:
  - huggingface_hub
  - requests
  - langgraph
  - langchain-core
  - langsmith
  - pydantic
  - orjson
  - numpy
  - pandas
  - tqdm
  - jupyter
  - pytest
  - black
  - isort
  - flake8
